spring.application.name=kafka
management.endpoints.web.exposure.include=*
#wsl hostname -I
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=exchange-rate-indexer
exchange.kafka.topic=exchange-rates
exchange.elasticsearch.index=forex-data
spring.elasticsearch.uris=http://localhost:9200
server.port=8081
exchange.api.url=https://api.exchangerate-api.com/v4/latest/USD
exchange.polling.fixed-delay-ms=30000
exchange.polling.initial-delay-ms=30000
